<div class="form-group">
	<label for="name" class="col-xs-3 col-sm-4 control-label">naam</label>
	<div class="col-xs-8 col-sm-6">
		<input type="text" class="form-control" id="name" name="name" maxlength="<?= Voetbal_Association::MAX_NAME_LENGTH ?>" value="<?= $this->oAssociation !== null ? $this->oAssociation->getName() : null ?>" placeholder="bondnaam">
	</div>
</div>
<div class="form-group">
	<label for="description" class="col-xs-3 col-sm-4 control-label">omschrijving</label>
	<div class="col-xs-8 col-sm-6">
		<input type="text" class="form-control" id="description" name="description" value="<?= $this->oAssociation !== null ? $this->oAssociation->getDescription() : null ?>" placeholder="bondomschrijving">
	</div>
</div>

<?php if ( $this->oAssociation !== null ): ?>
	<input type="hidden" name="associationid" value="<?= $this->oAssociation->getId() ?>">
<?php endif; ?>