<h2 style="text-align:center;">nieuws</h2>

<hr>

<div itemscope itemtype="http://schema.org/NewsArticle">
    <div class="row">
        <h3 itemprop="headline" class="col-sm-8" style='margin-top:0px;'>EK 2024 Duitsland</h3>
        <span class="col-sm-4" style="font-size: 90%">15 mei 2024</span>
    </div>
    <p itemprop="articleBody">
        <img style="float:left; margin-right:7px;" itemprop="image" width="50" height="50" src="<?= Zend_Registry::get("baseurl") ?>public/images/logo_50.png" alt="logo voetbaloog"/>
        Iedereen klaar voor de EK editie in Duitsland? Maak nu een voetbalpool aan om samen met je familie, vrienden, kennissen of collega's mee te spelen. Zo krijgen de wedstrijden nog meer spanning.<br><br>
        Veel plezier!<br>
    </p>
    <meta itemprop="datePublished" content="2024-05-15T16:23:00+08:00"/>
</div>

<hr>

<div itemscope itemtype="http://schema.org/NewsArticle">
    <div class="row">
        <h3 itemprop="headline" class="col-sm-8" style='margin-top:0px;'>Wineke wint pool "Familie Duim" (WK 2022)</h3>
        <span class="col-sm-4" style="font-size: 90%">15 juli 2022</span>
    </div>
    <p itemprop="articleBody">
        <img width="150" height="200" style="float:left; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2022_famduim_150_200.jpg" alt="foto winnaar pool ek 2024 Familie Duim">
        Wineke van harte gefeliciteerd met het behalen van de eerste plaats.
        Het was een spannende strijd. Uiteindelijk ben je 3 punten op Rodin en 4 punt op Storm voorgebleven!
        Bekijk hier <a href="<?= Zend_Registry::get("baseurl"); ?>default/pool/standallertijden/poolid/33/">de ranglijst aller tijden</a>
        <br/><br/><br/><br/><br/>
    </p>
    <meta itemprop="datePublished" content="2024-06-25T11:30:00+02:00"/>
</div>

<hr>

<div class="row" itemscope itemtype="http://schema.org/NewsArticle">
    <div class="col-sm-8">
        <h3 itemprop="headline" style='margin-top:0px;'>Gerrit wint pool "Familie Duim" (EK 2021)</h3>
        <p itemprop="articleBody">

            Gerrit van harte gefeliciteerd met het behalen van de eerste plaats. Eindelijk is het dan zo ver.
            Je hebt je terug geknokt uit een verslagen positie en bent nu toegetreden tot de "VoetbalOog-Hall Of Fame".
            Bets voert nu de <a href="<?= Zend_Registry::get("baseurl"); ?>default/pool/standallertijden/poolid/11/">ranglijst aller tijden</a> aan, gevolgd door Coen en Dineke.
        </p>
    </div>
    <div class="col-sm-4">
        <div style="font-size: 90%">15 aug 2021</div>
        <img width="150" height="200" style="float:right; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2021_famduim_150_200.jpg" alt="foto winnaar pool ek 2021 Familie Duim">
    </div>
    <meta itemprop="datePublished" content="2021-08-15T16:23:00+08:00"/>
</div>
<hr>

<div itemscope itemtype="http://schema.org/NewsArticle">
    <div class="row">
        <h3 itemprop="headline" class="col-sm-8" style='margin-top:0px;'>Folkher wint pool "Familie Duim" (WK 2018)</h3>
        <span class="col-sm-4" style="font-size: 90%">15 juli 2020</span>
    </div>
    <p itemprop="articleBody">
        <img width="150" height="200" style="float:left; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2018_famduim_150_200.jpg" alt="foto winnaar pool wk 2018 Familie Duim">
        Folkher van harte gefeliciteerd met het behalen van de eerste plaats.
        Je was al vrij snel kampioen, omdat diegene die je konden inhalen dezelfde voorspellingen hadden als jou.
        Je staat mooi op de foto met de felbegeerde beker!
        Coen heeft Bets nu ingehaald op <a href="<?= Zend_Registry::get("baseurl"); ?>default/pool/standallertijden/poolid/33/">de ranglijst aller tijden</a> aa. Gerrit, Dineke en Folkher volgen op enige afstand.
        <br/><br/><br/>
    </p>
    <meta itemprop="datePublished" content="2021-07-15T11:30:00+02:00"/>
</div>

<hr>

<div itemscope itemtype="http://schema.org/NewsArticle">
	<div class="row">
		<h3 itemprop="headline" class="col-sm-8" style='margin-top:0px;'>Duncan wint pool "Familie Duim" (EK 2016)</h3>
		<span class="col-sm-4" style="font-size: 90%">18 jul 2018</span>
	</div>
	<p itemprop="articleBody">
		<img width="150" height="200" style="float:right; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2016_famduim_150_200.jpg" alt="foto winnaar pool ek 2016 Familie Duim">
		Duncan van harte gefeliciteerd met het behalen van de eerste plaats.
		Het was spannend tot aan de finale! Doordat hij boven Coen is ge&euml;indigd heeft hij een gebakje verdiend.
		Hiernaast heeft Duncan ook de geldprijs en natuurlijk de felbegeerde beker gewonnen!
		Thijs deed ook nog lang mee voor de prijzen, maar werd door het verlies van
		Duitsland op Itali&euml; helaas uitgeschakeld voor de eerste prijs.
		Bets voert nu de <a href="<?= Zend_Registry::get("baseurl"); ?>default/pool/standallertijden/poolid/11/">ranglijst aller tijden</a> aan, gevolgd door Coen en Dineke.
	</p>
	<meta itemprop="datePublished" content="2016-07-18T16:30:00+08:00"/>
</div>

<hr>

<h3 style='margin-top:0px;'>Joris wint pool "Familie Duim" (WK 2014)</h3>
<img width="150" height="200" style="float:left; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2014_famduim_150_200.jpg" alt="foto winnaar pool wk 2014 Familie Duim">
<p>
Joris van harte gefeliciteerd met het behalen van de eerste plaats. Diana had bijna haar titel geprolongeerd, maar
doordat Duitsland de finale won, is dit niet gebeurd. Aan de ene kant jammer omdat Duitsland de titel heeft gepakt,
maar voor jou mooi. Duitsland was overigens de terechte kampioen. Bij het EK 2016 in Frankrijk heeft iedereen weer
nieuwe kansen om de beste voetbalmanager te worden. Diana is Dineke gepasseerd op de ranglijst aller tijden. Het is
nu zeer spannend. Diana, Dineke en Bets staat allemaal 1 punt van elkaar. Klik <a href="<?php echo Zend_Registry::get("baseurl"); ?>pool/index/poolid/6/">hier</a> om deze ranglijst te bekiijken.
</p>
<div style='clear:both;'></div>

<hr>

<h3 style='margin-top:0px;'>Diana wint pool "Familie Duim" (EK 2012)</h3>
<img width="150" height="200" style="float:right; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2012_famduim_150_200.jpg" alt="foto winnaar pool ek 2012 Familie Duim">
<p>
Diana van harte gefeliciteerd met het behalen van de eerste plaats. Nadat de eerste twee keer een man heeft gewonnen
is het nu voor de tweede keer achtereen dat een vrouw heeft gewonnen. De stand tussen de mannen en vrouwen is hiermee
op twee twee gekomen. Je was bijna uit de competitie gehaald omdat je te laat had betaald, maar dat zullen we deze
keer maar over het hoofd zien, alhoewel Folkher het hier niet mee eens was. Dineke staat nog steeds bovenaan in de
ranglijst allertijden. Klik <a href="<?php echo Zend_Registry::get("baseurl"); ?>pool/index/poolid/6/">hier</a> om deze ranglijst te bekiijken.
</p>

<hr>

<h3 style='margin-top:0px;'>Betsy wint pool "Familie Duim" (WK 2010)</h3>
<img width="150" height="200" style="float:left; margin: 10px; border-radius:8px;" src="<?php echo Zend_Registry::get("baseurl"); ?>public/images/website/winnaar2010_famduim_150_200.jpg" alt="foto winnaar pool wk 2010 Familie Duim">
<p>Betsy de Wilde heeft door de eerste plaats van het wk 2010 nieuw elan gekregen om nu ook te proberen
op de ranglijst aller tijden van de pool "Familie Duim" alleen bovenaan te komen. Tevens wil ze graag de schitterende
bokaal nog 2 jaar op haar kast zien prijken. Voor de eerste plaats op de ranglijst aller tijden zijn echter een aantal
gegadigden. Dineke staat nu op de eerste plaats, daarna volgt Coen op 1 punt. Ben en Ineke staan daar weer 1 punt achter.
Betsy staat daar weer een punt achter en daarna volgt een gat naar de nummer 6 Diana. Dineke en Ineke hebben echter nog
geen pool gewonnen maar staan door hun steevaste goede voorspellingen toch bij de bovensten. Klik
<a href="<?php echo Zend_Registry::get("baseurl"); ?>pool/index/poolid/4/">hier</a> voor de ranglijst.
Verder zijn de beloningen voor een correct voorspeld resultaat of een correct voorspelde score in de eerste ronde
opgehoogd met 1 punt.
De pool "Familie Duim" gaat aankomende ek voor de vierde keer van start en bij deze wil ik iedereen
vast succes wensen!
</p>