<div class="row">
	<div class="btn-group btn-group-justified">
		<a style="padding-top: 10px; padding-bottom: 10px;" href="<?= Zend_Registry::get("baseurl") ?>pool/aanmaken/" class="btn btn-default" role="button">aanmaken</a>
		<a style="padding-top: 10px; padding-bottom: 10px;" href="<?= Zend_Registry::get("baseurl") ?>" class="btn btn-default" role="button">pools</a>
		<a style="padding-top: 10px; padding-bottom: 10px;" href="<?= Zend_Registry::get("baseurl") ?>pool/meedoen/" class="btn btn-default" role="button">meedoen</a>
	</div>
</div>