<?php

if ( ( Source_Db::ACTION_INSERT & $this->auth ) !== Source_Db::ACTION_INSERT )
	return;

echo "<form name=\"adduserform\" method=\"POST\" action=\"".$this->url."/\">";
echo "<fieldset><legend>Databasegebruiker toevoegen</legend>";
echo "<table>";
if ( $this->message !== null )
	echo "<tr><td colspan=3>".$this->message."<br></td></tr>";
echo "<tr><td>Gebruikersnaam</td><td> : </td><td><input type=\"text\" name=\"newuserid\" value=\"".$this->newuserid."\"></td></tr>";
$cfgAuth = new Zend_Config_Ini(APPLICATION_PATH.'/configs/config.ini', 'auth');
if ( $cfgAuth->logintype === "database" )
{
	echo "<tr><td>Wachtwoord</td><td> : </td><td><input type=\"password\" name=\"password\" value=\"".$this->password."\"></td></tr>";
	echo "<tr><td>Herhaal wachtwoord</td><td> : </td><td><input type=\"password\" name=\"repeatpassword\" value=\"".$this->repeatpassword."\"></td></tr>";
}
echo "<tr><td colspan=3 align=right><input type=\"submit\" name=\"btnadd\" value=\"Opslaan\"></td></tr>";
echo "</table>";
echo "</fieldset>";
echo "</form><br>";

?>