<div align=center>

<h2>doneren</h2>
<h6>
Je kunt je donatie doen met behulp van paypal.<br/>
Je donatie zal volledig ten goede komen van deze website en de ontwikkeling ervan.<br/>
Op deze manier proberen we de website reclame-vrij te houden.<br/>
</h6>

<form action="https://www.paypal.com/cgi-bin/webscr" target="_blank" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="DUNNRY4AK36LG">
<input type="image" src="https://www.paypalobjects.com/nl_NL/NL/i/btn/btn_donateCC_LG.gif" style="border:0" name="submit" alt="PayPal, de veilige en complete manier van online betalen.">
<img alt="" border="0" src="https://www.paypalobjects.com/nl_NL/i/scr/pixel.gif" width="1" height="1">
</form>

</div>