<? foreach ($this->providers as $provider):?>
	<dl>
		<dt style="font-weight: bold;">Provider name</dt>
		<dd style="font-weight: bold;"><? echo $provider->getName(); ?></dd>

		<dt>Id from provider</dt>
		<dd><?=$provider->getId(); ?></dd>
	<?
	if($provider->getName()=='facebook'):
	?>
		<dt>Profile</dt>
		<dd>
			<dl>
			<?
			$profile = $provider->getApi()->getProfile();
			foreach($profile as $key => $value):
			?>
				<dt><?= $key ?></dt><dd><?=  (is_object($value)) ?  "Cannot convert to string" : $value ?></dd>
			<?
			endforeach;
			?>
			</dl>
		</dd>
		<dt>Picture</dt>
		<dd>
			<img src="<?=$provider->getApi()->getPicture(); ?>">
		</dd>
	<?
	endif;
	if($provider->getName()=='twitter'):
	?>
		<dt>Profile</dt>
		<dd>
			<dl>
			<?
			$profile = $provider->getApi()->getProfile();
			foreach($profile as $key => $value):
			?>
				<dt><?= $key ?></dt>
				<dd><?=  (is_object($value)) ?  "Cannot convert to string" : $value ?></dd>
			<?
			endforeach;
			?>
			</dl>
		</dd>
		<dt>Picture</dt>
		<dd>
			<img src="<?=$provider->getApi()->getPicture(); ?>">
		</dd>
	<?
	endif;
	if($provider->getName()=='google'):
	?>
		<dt>Profile</dt>
		<dd>
			<dl>
			<?
			$profile = $provider->getApi()->getProfile();
			foreach($profile as $key => $value):
			?>
				<dt><?= $key ?></dt>
				<dd><?=  (is_object($value)) ?  "Cannot convert to string" : $value ?></dd>
			<?
			endforeach;
			?>
			</dl>
		</dd>
	<?
	endif;
	?>
	</dl>
<?
endforeach;
?>