
<div class="page-header" style="text-align: center;">
	<h2>nieuw wachtwoord aanvragen</h2>
</div>

<?php if( $this->oUser !== null ): ?>
	<div class="alert alert-danger">je bent al ingelogd en kunt dus je wachtwoord niet vergeten zijn!</div>
	<?php return; ?>
<?php endif ?>

<?php if( strlen( $this->errormessage ) > 0 ): ?>
	<div class="alert alert-danger"><?= $this->errormessage ?></div>
<?php endif ?>

<?php if( strlen( $this->successmessage ) > 0 ): ?>
	<div class="alert alert-success"><?= $this->successmessage ?></div>
	<?php return; ?>
<?php endif ?>

<form role="form" action="<?= $this->url; ?>/" method="post" class="form-horizontal" role="form">
	<div class="form-group">
		<label for="username" class="col-sm-3 control-label">emailadres</label>
		<div class="col-sm-9">
			<input type="text" class="form-control" id="username" name="username" placeholder="emailadres">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<button type="submit" class="btn btn-default" name="btnsubmit" value="submitted" >vraag nieuw wachtwoord aan</button>
		</div>
	</div>
</form>

<script type="text/javascript">
	document.getElementById("username").focus();
</script>
