
<div class="page-header" style="text-align: center;">
	<h2>wachtwoord wijzigen</h2>
</div>

<?php if( strlen( $this->successmessage ) > 0 ): ?>
	<div class="alert alert-success">je wachtwoord is aangepast, klik <a role="button" class="btn btn-default" href="<?= Zend_Registry::get("baseurl") ?>user/login/username/coen/">hier</a> om in te loggen</div>
	<?php return; ?>
<?php endif ?>

<?php if( strlen( $this->errormessage ) > 0 ): ?>
	<div class="alert alert-danger"><?= $this->errormessage ?></div>
<?php endif ?>

<form role="form" action="<?= $this->url; ?>/" method="post" class="form-horizontal" role="form">
	<div class="form-group">
		<label for="usernamedisabled" class="col-sm-3 control-label">gebruikersnaam</label>
		<div class="col-sm-9">
			<input type="text" class="form-control" name="usernamedisabled" value="<?= $this->oInputUser !== null ? $this->oInputUser->getName() : null ?>" disabled>
		</div>
	</div>
	<div class="form-group">
		<label for="password" class="col-sm-3 control-label">wachtwoord</label>
		<div class="col-sm-9">
			<input type="password" class="form-control" id="password" name="password" placeholder="wachtwoord">
		</div>
	</div>
	<div class="form-group">
		<label for="repeatpassword" class="col-sm-3 control-label">herhaal wachtwoord</label>
		<div class="col-sm-9">
			<input type="password" class="form-control" id="repeatpassword" name="repeatpassword" placeholder="herhaal wachtwoord">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<button type="submit" class="btn btn-default" name="btnsubmit" value="submitted" >wijzig wachtwoord</button>
		</div>
	</div>
	<input type="hidden" name="userid" value="<?= $this->oInputUser !== null ? $this->oInputUser->getId() : null ?>">
	<input type="hidden" name="hash" value="<?= $this->hash; ?>">
</form>

<script type="text/javascript">
	document.getElementById("password").focus();
</script>