<div id="page-pool-admin"></div>



<div class="row" style="margin-top: 5px;">
	<div class="col-xs-2" style="padding-left: 0px;">
		<a role="button" class="btn btn-default" href="<?= Zend_Registry::get( "baseurl" ) ?>pool/index/poolid/<?= $this->oPool->getId() ?>/"><span class="glyphicon glyphicon-hand-left"></span> pool</a>
	</div>
	<div class="col-xs-10" style="text-align: center; padding-right: 0px;">
		<h3><span class="glyphicon glyphicon-cog"></span> poolbeheer <span class="glyphicon glyphicon-cog"></span></h3>
	</div>
</div>