<?php
	$oOptions = Construction_Factory::createOptions();
	$oOptions->addOrder( "Voetbal_Association::Name", false );
	$oAssociations = Voetbal_Association_Factory::createObjectsFromDatabase( $oOptions );

	$oAssociationComboBox = Controls_Factory::createComboBox("associationid");
	$oAssociationComboBox->putSource( $oAssociations );
	$oAssociationComboBox->putCSSClass( "form-control" );
	if ( $this->oTeam !== null )
		$oAssociationComboBox->putObjectToSelect( $this->oTeam->getAssociation() );
	$oAssociationComboBox->putObjectPropertyToShow( "**Voetbal_Association::Name** ( **Voetbal_Association::Description** )" );
?>

<div class="form-group">
	<label for="name" class="col-sm-4 control-label">naam</label>
	<div class="col-sm-8">
		<input type="text" class="form-control" id="name" name="name" maxlength="<?= Voetbal_Team::MAX_NAME_LENGTH ?>" value="<?= $this->oTeam !== null ? $this->oTeam->getName() : null ?>" placeholder="teamnaam">
	</div>
</div>
<div class="form-group">
	<label for="abbreviation" class="col-sm-4 control-label">afkorting</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="abbreviation" name="abbreviation" value="<?= $this->oTeam !== null ? $this->oTeam->getAbbreviation() : null ?>" placeholder="afkorting">
	</div>
</div>
<div class="form-group">
	<label for="imagename" class="col-sm-4 control-label">afbeeldingsnaam</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="imagename" name="imagename" value="<?= $this->oTeam !== null ? $this->oTeam->getImageName() : null ?>" placeholder="afbeeldingsnaam">
	</div>
</div>
<div class="form-group">
	<label for="associationid" class="col-sm-4 control-label">bond</label>
	<div class="col-sm-4">
		<?= $oAssociationComboBox ?>
	</div>
</div>

<?php if ( $this->oTeam !== null ): ?>
	<input type="hidden" name="teamid" value="<?= $this->oTeam->getId() ?>">
<?php endif; ?>
