<!DOCTYPE HTML>
<html lang="nl" ng-app="voetbal">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="keywords" content="voetbalpool,voetbal,pool,wk,ek" />
	<meta name="description" content="VoetbalOog, gratis voetbalpool voor ek en wk voetbal. Doe mee met je familie, vrienden, kennissen of collega's.">
	<title>VoetbalOog, voetbalmanager voor het ek en wk</title>
	<link rel="shortcut icon" href="/favicon/favicon.ico">
	<link rel="icon" sizes="16x16 32x32 64x64" href="/favicon/favicon.ico">
	<link rel="icon" type="image/png" sizes="192x192" href="/favicon/favicon-192.png">
	<link rel="icon" type="image/png" sizes="160x160" href="/favicon/favicon-160.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96.png">
	<link rel="icon" type="image/png" sizes="64x64" href="/favicon/favicon-64.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/favicon/favicon-152.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/favicon/favicon-144.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/favicon/favicon-120.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/favicon/favicon-114.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/favicon/favicon-76.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/favicon/favicon-72.png">
	<link rel="apple-touch-icon" href="/favicon/favicon-57.png">
	<meta name="msapplication-TileColor" content="#FFFFFF">
	<meta name="msapplication-TileImage" content="/favicon/favicon-144.png">
	<meta name="msapplication-config" content="/favicon/browserconfig.xml">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<script type="text/javascript">var g_sPubMap = "<?= Zend_Registry::get("baseurl"); ?>";</script>

	<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/bootstrap-3.3.4/css/bootstrap.min.css">
	<?php if ( APPLICATION_ENV === "production" ): ?>
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/min-1.0.0.css">
	<?php else: ?>
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/voetbaloog.css">
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/flaticon.css">
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/bootstrap_custom.css">
	<?php endif ?>

	<?php if ( $this->angular === true ): ?>
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('jsthirdparties'); ?>noUiSlider.8.1.0/nouislider.css">
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('jsthirdparties'); ?>css-progress-wizard/css/progress-wizard<?= ( APPLICATION_ENV === "production" ) ? ".min" : null ?>.css" >
		<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseurl'); ?>public/styles/draganddrop.css" >
	<?php endif; ?>

	<?= $this->layout()->extracssincludes; ?>

	<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script>
	<script src='<?= Zend_Registry::get("baseurl"); ?>jsthirdparties/jquery.mobile.custom.min.js'></script>
	<script src='<?= Zend_Registry::get('baseurl'); ?>public/styles/bootstrap-3.3.4/js/bootstrap.min.js'></script>
	<script src='<?= Zend_Registry::get("jslibrary"); ?>IManager.js'></script>

	<?php if ( APPLICATION_ENV === "production" ): ?>
		<script src="<?= Zend_Registry::get("jslibrary") ?>min-1.0.0.js"></script>
	<?php else: ?>
		<script src="<?= Zend_Registry::get("jslibrary"); ?>Point.js"></script>
		<script src="<?= Zend_Registry::get("jslibrary"); ?>DivHelper.js"></script>
		<script src="<?= Zend_Registry::get("jslibrary"); ?>AssociativeArray.js"></script>
	<?php endif ?>

	<?php if ( $this->angular === true ): ?>
		<script src='//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js'></script>
		<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-sanitize.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-resource.js"></script>
		<script src='<?= Zend_Registry::get('jsthirdparties'); ?>ui-bootstrap-tpls-0.14.1.js'></script>
		<script src='<?= Zend_Registry::get('jsthirdparties'); ?>noUiSlider.8.1.0/nouislider.js'></script>
		<script src='<?= Zend_Registry::get('jsthirdparties'); ?>nouislider-angular/nouislider.js'></script>
		<script src='<?= Zend_Registry::get('jsthirdparties'); ?>angular-dragdrop/draganddrop.js'></script>
	<?php endif ?>

	<?= $this->layout()->extrajsincludes; ?>

	<script src="<?= Zend_Registry::get("baseurl"); ?>jsthirdparties/jsvoetbal/jquery/voetbal.js"></script>
	<script src="<?= Zend_Registry::get("jsmap"); ?>custom.js" ></script>

	<script type="text/javascript">var g_jsonVoetbal = <?= json_encode( new Voetbal_JSON() );?></script>
</head>
<body>
<nav class="navbar navbar-default header">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<h1>
			<a class="navbar-brand menu" href="<?= Zend_Registry::get("baseurl") ?>"><img alt="VoetbalOog" width="20" height="20" style="float: left; margin-right:5px;" src="<?= Zend_Registry::get("baseurl") ?>public/images/logo_20.png">VoetbalOog</a>
		</h1>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="navbar">
		<ul class="nav navbar-nav">
			<?php if( $this->arrMenuItems !== null ): ?>
				<?php foreach( $this->arrMenuItems as $sName => $arrMenuItem ): ?>
					<?php $sName = array_key_exists("nicename", $arrMenuItem ) ? $arrMenuItem["nicename"] : $sName; ?>
					<li class="<?= $arrMenuItem["activeclass"] ? "active" : null ?>">
						<a class="menu" href="<?= Zend_Registry::get("baseurl") . $arrMenuItem["action"] ?>poolid/<?= $this->oPool->getId() ?>/">
							<?php if( array_key_exists("glyph", $arrMenuItem ) ): ?><span class="<?= $arrMenuItem["glyph"] ?>"></span><?php endif; ?><?= $sName ?>
						</a>
					</li>
				<?php endforeach; ?>
			<?php endif; ?>
			<?php
			$arrAdminList = null;
			if ( $this->oUser !== null )
			{
				if ( $this->oUser->hasRole( "superadmin" ) )
				{
					$arrAdminList = array(
						"competities" => "voetbal/competitie/index/",
						"standaard<br>voorspelinstellingen" => "voorspelinstellingen/competitieseizoen/",
						"voorspellingen" => "voorspellingenbijwerken/index/",
						"teams" => "voetbal/team/index/",
						"personen" => "voetbal/persoon/index/",
						"seizoenen" => "voetbal/seizoen/index/",
						"bonden" => "voetbal/bond/index/",
						"divider1" => "divider",
						"extern" => "voetbal/import/index/",
						"divider2" => "divider",
						"rollen, acties & menu" => "admin/autorisatie/index/",
						"database" => "admin/database/index/",
						"gebruikers" => "admin/gebruikersbeheer/index/",
						"simuleer" => "admin/simuleer/index/"
					);
					// get latest comp season
					$oOptions = Construction_Factory::createOptions();
					$oOptions->addLimit(1);
					$oCompetitionSeason = Voetbal_CompetitionSeason_Factory::createObjectsFromDatabaseCustom( true, false, $oOptions )->first();
					if ( $oCompetitionSeason !== null )
						$arrAdminList = array_merge( array( $oCompetitionSeason->getAbbreviation() => "voetbal/competitieseizoen/index/?id=".$oCompetitionSeason."&subject=planning" ), $arrAdminList);
				}
			}
			?>
			<?php if( $arrAdminList!==null ): ?>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">adm<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<?php foreach ( $arrAdminList as $sName => $sAction ): ?>
							<?php if( $sAction === "divider" ): ?>
								<li class="divider"></li>
							<?php else: ?>
								<li><a href="<?= Zend_Registry::get("baseurl") . $sAction ?>"><?= $sName ?></a></li>
							<?php endif ?>
						<?php endforeach ?>
					</ul>
				</li>
			<?php endif ?>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li>
				<?php if( $this->oUser === null ): ?>
					<a class="menu" href="<?= Zend_Registry::get('baseurl'); ?>user/login/">
						<span class="glyphicon glyphicon-log-in"></span>&nbsp;<span>inloggen</span>
					</a>
				<?php else: ?>
					<a class="menu" href="<?= Zend_Registry::get('baseurl'); ?>user/home/">
						<span class="glyphicon glyphicon-user"></span>&nbsp;<span><?= $this->oUser->getName() ?></span>
					</a>
				<?php endif ?>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
<div id="content">
	<?= $this->layout()->content; ?>
</div>
<footer class="footer container">
	<div class="row" id="ft">
		<div class="col-xs-12 col-sm-4">
			<h3>contact</h3>
			<div><span class="glyphicon glyphicon-phone"></span> +31 614363514</div>
			<div><span class="glyphicon glyphicon-envelope"></span> coendunnink@gmail.com</div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<h3>projecten</h3>
			<div><a target="_blank" href="https://www.superelf-eredivisie.nl/">superelf</a></div>
			<div><a target="_blank" href="https://www.fctoernooi.nl/">fc toernooi</a></div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<h3>links</h3>
			<div><a target="_blank" rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">cc by-nc-sa<span> 3.0 licentie</span></a></div>
			<div><a target="_blank" rel="license" href="http://www.flaticon.com/">flaticon.com</a></div>
		</div>
	</div>
	<div class="hidden-xs" style="text-align: center; padding-top:50px;"><span class="glyphicon glyphicon-copyright-mark"></span> Coen Dunnink</div>
</footer>
<!-- loadingModal -->
<div class="modal fade" id="loadingModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-body" align="center">
				<h2><span class="glyphicon glyphicon-refresh spin"></span></h2>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
	g_nUserId = <?= $this->oUser !== null ? $this->oUser->getId() : "null" ?>;
</script>
<?php if ( $this->angular === true ): ?>
	<script src='<?= Zend_Registry::get("jsthirdparties"); ?>jsvoetbal/angular/app.js'></script>
	<script src='<?= Zend_Registry::get("jsthirdparties"); ?>jsvoetbal/angular/competitionseason/structure.js'></script>
	<script src='<?= Zend_Registry::get("jsthirdparties"); ?>jsvoetbal/angular/competitionseason/teams.js'></script>
	<script src='<?= Zend_Registry::get("jsthirdparties"); ?>jsvoetbal/angular/competitionseason/games.js'></script>
<?php endif; ?>

</body>
</html>
