<?php
	$oCompetitionSeason = null;
	if ( $this->oCompetitionSeasons->count() === 1 )
		$oCompetitionSeason = $this->oCompetitionSeasons->first();

	$oComboBox = Controls_Factory::createComboBox( "competitionseasonid" );
	$oComboBox->putObjectToSelect( $oCompetitionSeason );
	$oComboBox->putSource( $this->oCompetitionSeasons );
	$oComboBox->putCSSClass( "form-control" );
	$oComboBox->putObjectPropertyToShow("**Voetbal_CompetitionSeason::Name**");
?>

<div class="panel panel-default">
	<div class="panel-body">
		<div id="errordiv_step1" class="alert alert-danger">
			<p class="alert-link">je moet een competitie kiezen</p>
		</div>

		<form role="form">
			<div class="form-group">
				<label for="competitionseasonid">competitie</label>
				<?= $oComboBox ?>
			</div>
		</form>
	</div>

	<div class="panel-footer">
		<div class="pull-right">
			<button id="btn_step1_next" type="button" class="btn btn-default">volgende <span class="glyphicon glyphicon-circle-arrow-right"></span></button>
		</div>
		<div style="clear:both"></div>
	</div>
</div>

<script type="text/javascript">
	var g_bCanChooseExistingPool = false;
</script>