<div class="container-fluid">
	<?php if ($this->subheader !== null): ?>
		<h5 class="hidden-xs pull-right" style="display: inline-block"><?= $this->subheader ?></h5>
	<?php endif; ?>
</div>
<div class="container-fluid">
	<div class="visible-xs">
		<h2 style="display: inline-block"><?= $this->sHeaderName ?></h2>
		<?php if ($this->subheader !== null): ?>
			<h4 style="display: inline-block"><?= $this->subheader ?></h4>
		<?php endif; ?>
	</div>
</div>
<hr>